/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface NetworkTable {
    'data'?: [string, string, string | number][];
    'filter': (predicate: (line: string[]) => boolean) => Promise<string[][]>;
    'height'?: string;
    'hood'?: any;
  }
}

declare global {


  interface HTMLNetworkTableElement extends Components.NetworkTable, HTMLStencilElement {}
  var HTMLNetworkTableElement: {
    prototype: HTMLNetworkTableElement;
    new (): HTMLNetworkTableElement;
  };
  interface HTMLElementTagNameMap {
    'network-table': HTMLNetworkTableElement;
  }
}

declare namespace LocalJSX {
  interface NetworkTable extends JSXBase.HTMLAttributes<HTMLNetworkTableElement> {
    'data'?: [string, string, string | number][];
    'height'?: string;
    'hood'?: any;
    'onNetwork-table.hover-off'?: (event: CustomEvent<void>) => void;
    'onNetwork-table.hover-on'?: (event: CustomEvent<string[]>) => void;
    'onNetwork-table.select'?: (event: CustomEvent<string[]>) => void;
  }

  interface IntrinsicElements {
    'network-table': NetworkTable;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


